FROM python:3.9.20-bullseye

RUN apt-get update --fix-missing && \
    apt-get install -y wget bzip2 ca-certificates curl git libfftw3-dev python3 pip && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

RUN ln -sf $(which python3.10) /usr/bin/python

# Upgrade pip and install required packages
RUN pip install hyperspy==1.6 && \
    pip install tensorflow==2.12 && \
    git clone https://github.com/Ivanlh20/tk_r_em.git /tk_r_em && \
    pip install -e /tk_r_em