__version__ = '1.0.5'
__name__ = 'tk_r_em'
__description__ = 'Deep convolutional neural networks to restore single-shot electron microscopy images'
__author__ = 'Ivan Lobato'
__author_email__='ivanlh20@gmail.com'
__url__ = 'https://github.com/Ivanlh20/r_em/'
__credits__ = 'University of Antwerp'
__license__ = 'GPLv3'